# Basic set up for three package managers

version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/pkg/cloudflare/worker/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    
## open-pull-requests-limit: 0 will only create security updates default