# Basic set up for three package managers

version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
     - "/pkg/cloudflare/worker/"
     - "/pkg/cloudflare/decisions-sync-worker/"
    schedule:
      interval: "weekly"
    
## open-pull-requests-limit: 0 will only create security updates default
