version: "2"

linters:
  default: all
  disable:
    - fatcontext
    - interfacebloat
    - perfsprint
    - unparam
    - nilerr
    - containedctx
    - promlinter
    - thelper
    - nestif
    - ireturn
    - testpackage
    - embeddedstructfieldcheck
    - funcorder
    - godoclint
    - noinlineerr
    - wsl_v5

    - cyclop    # revive
    - funlen    # revive
    - gocognit  # revive
    - gocyclo   # revive
    - lll       # revive

    - godot                 # Check if comments end in a period
    - gosec                 # (gas): Inspects source code for security problems
    - inamedparam           # reports interfaces with unnamed method parameters
    - wrapcheck             # Checks that errors returned from external packages are wrapped
    - mnd                   # An analyzer to detect magic numbers.
    - nlreturn              # nlreturn checks for a new line before return and branch statements to increase code clarity
    - whitespace            # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.
    - wsl                   # add or remove empty lines
    - godox                 # Tool for detection of FIXME, TODO and other comment keywords
    - err113                # Go linter to check the errors handling expressions
    - paralleltest          # Detects missing usage of t.Parallel() method in your Go test
    - exhaustruct           # Checks if all structure fields are initialized
    - gochecknoglobals      # Check that no global variables exist.
    - goconst               # Finds repeated strings that could be replaced by a constant
    - tagliatelle           # Checks the struct tags.
    - varnamelen            # checks that the length of a variable's name matches its scope
    - prealloc

  settings:

    depguard:
      rules:
        yaml:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: yaml.v2 is deprecated for new code in favor of yaml.v3

    errcheck:
      check-type-assertions: false

    gocritic:
      enable-all: true
      disabled-checks:
        - captLocal
        - commentFormatting
        - emptyStringTest
        - hugeParam
        - rangeValCopy
        - paramTypeCombine
        - wrapperFunc

    govet:
      disable:
        - fieldalignment
      enable-all: true

    maintidx:
      # raise this after refactoring
      under: 17

    misspell:
      locale: US

    nlreturn:
      block-size: 5

    nolintlint:
      require-explanation: false  # don't require an explanation for nolint directives
      require-specific: false     # don't require nolint directives to be specific about which linter is being skipped
      allow-unused: false         # report any unused nolint directives

    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          arguments:
            # lower this after refactoring
            - 87
        - name: comment-spacings
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: context-as-argument
          disabled: true
        - name: cyclomatic
          arguments:
            # lower this after refactoring
            - 49
        - name: deep-exit
          disabled: true
        - name: empty-lines
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          arguments:
            # lower this after refactoring
            - 69
            - 187
        - name: if-return
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          arguments:
            # lower this after refactoring
            - 240
        - name: max-public-structs
          disabled: true
        - name: package-directory-mismatch
          disabled: true
        - name: var-naming
          disabled: true
        - name: unexported-naming
          disabled: true
        - name: unnecessary-format
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: use-errors-new
          disabled: true

    staticcheck:
      checks:
        - all
        - -QF1004
        - -ST1003
        - -ST1012

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:

      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration'

    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/crowdsecurity)
        - prefix(github.com/crowdsecurity/cs-cloudflare-worker-bouncer)

  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
